### PR TITLE
Added italian language support

### PR DESCRIPTION
**Pull request by Dazorn96**
- Created and translated italian language file (100%)

I hope i edited all code needed to let it work.

### CODE REVIEW

**Comment by JulienCoutault** [comment]
Thanks for your contributing, i will try it this evening

**Comment by JulienCoutault** [comment]
I saw you forgot a file, i open a pull request [#1](https://github.com/Dazorn96/lindo/pull/1) on your repo to help you

**Comment by Dazorn96** [comment]
All should be good now :)

**Comment by JulienCoutault** [comment]
Sorry i made a mistake,

Can you replace 

    'es': require(Application.appPath + `/dist/electron/i18n/it`)

by 

    'it': require(Application.appPath + `/dist/electron/i18n/it`)

in `electron/settings/settings.ts` line 41

And promised, after that will be done :grimacing:

**Comment by Dazorn96** [comment]
Done ;)

**Comment by JulienCoutault** [comment]
Thanks, i warn others

**Comment by Clover-Lindo** [comment]
Merging, I'll test this in the following week, and if everything's working well we'll do a release!

**Pull request merged**
