### PR TITLE
New translante pt-br

### PR DESCRIPTION
**Pull request by Nithack**
added new translation for Lindo.

translation created: PT-BR (Brazilian Portuguese)

Changed files:
settings.ts
general.componets.ts

Released Files:
pt.json
pt.js

### CODE REVIEW

**Comment by JulienCoutault** [comment]
Nice

**Comment by JulienCoutault** [comment]
I add missing code to include.
When you will finish the translation (if it is not already done), we will merge it

**Review by JulienCoutault — APPROVED** [review]

**Comment by JulienCoutault** [comment]
@Nithack Any news ?

**Comment by Nithack** [comment]
I'm going to update tonight. =D

**Pull request merged**
