### PR TITLE
update user agent, remove old android version, add new tablette/phone

### PR DESCRIPTION
**Pull request by aejii**

### CODE REVIEW

**Comment by Kedaostram** [comment]
Hey !
Don’t know what happened, I lost my other github account.

Here is my UA
`Mozilla/5.0 (iPhone; CPU iPhone OS 15_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Mobile/15E148 Safari/604.1`

**Comment by Kedaostram** [comment]
Maybe you should also update the default user agent in `electron/settings/settings-default.ts` ?

Current default value is `user_agent: 'Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-N920T Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36'`

**Comment by aejii** [comment]
> Maybe you should also update the default user agent in `electron/settings/settings-default.ts` ?
> 
> Current default value is `user_agent: 'Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-N920T Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36'`

J'ai update avec le 1er commit de cette pr [[b45f69f](https://github.com/prixe/lindo/pull/193/commits/b45f69f42a78605e1f7dc1a64c661c525d890cc5)](https://github.com/prixe/lindo/pull/193/commits/b45f69f42a78605e1f7dc1a64c661c525d890cc5)

**Comment by Kedaostram** [comment]
> > Maybe you should also update the default user agent in `electron/settings/settings-default.ts` ?
> > Current default value is `user_agent: 'Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-N920T Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36'`
> 
> J'ai update avec le 1er commit de cette pr [[b45f69f](https://github.com/prixe/lindo/pull/193/commits/b45f69f42a78605e1f7dc1a64c661c525d890cc5)]([b45f69f](https://github.com/prixe/lindo/commit/b45f69f42a78605e1f7dc1a64c661c525d890cc5))

J'avais pas vu !

**Pull request closed without merging**
